### ISSUE TITLE
ladvd stuck in sock_alloc_send_pskb/skb_recv_datagram

### ISSUE THREAD

**Issue by ttarabula** [sspans/ladvd#18]
Running from the latest on github as of today, we're seeing the following scenario:

ladvdc hangs before printing the first device (ctrl-c is necessary):

```
$ ladvdc
Capability Codes:
	r - Repeater, B - Bridge, H - Host, R - Router, S - Switch,
	W - WLAN Access Point, C - DOCSIS Device, T - Telephone, O - Other

Device ID                      Local Intf    Proto   Hold-time    Capability    Port ID
^C
```

The ladvd child seems to be in skb_recv_datagram and the parent in sock_alloc_send_pskb, before, during, and running ladvdc.

```
%CPU %MEM PSR   LIM WCHAN                             NI PAGEIN   LWP   PID  PPID PRI   RSS  STARTED S     TIME    SZ TT         UID USER        VSZ COMMAND
 0.0  0.0   0    xx sock_alloc_send_pskb               0      0  5242  5242     1  19 18240   Mar 04 S 00:00:00 12344 ?            0 root      49376   ladvd: parent [priv]
 0.0  0.0   2    xx skb_recv_datagram                  0      0  5244  5244  5242  19   704   Mar 04 S 00:00:00  8041 ?          100 ladvd     32164    ladvd: child       
 0.0  0.0   4    xx skb_recv_datagram                  0      0  8720  8720  8443  19   640 10:51:02 S 00:00:00  5420 pts/0        0 root      21680         ladvdc
```

Restarting ladvd (sigkill is necessary) fixes the problem, at least temporarily, so it feels like a race or deadlock of some sort, perhaps?

Note that this is running on Debian Wheezy with kernel 3.14.32, libc 2.17.

**Comment by sharewax** [comment]
I've found the same issue at Centos 7.
It happens, if some network changes was happened (restart network, adding new interfaces, etc).

**Comment by sspans** [comment]
Thanks for reporting the issue!

It's clear that something is up with the netlink support in combination with centos/rhel7.
I'll investigate this asap.
