### ISSUE TITLE
release doesn't contain configure script

### ISSUE THREAD

**Issue by sharewax** [sspans/ladvd#20]
Hello.
As I remember, you have said, that releases file should contain all needed files for build.
I've taken it from https://github.com/sspans/ladvd/releases, but I got 
```
+ ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --docdir=/usr/share/doc/ladvd
/var/tmp/rpm-tmp.tqAwiH: line 38: ./configure: No such file or directory
```
Probably we or you need to do something?
Can you help me with preparing this environment in future?
Thank you.

**Comment by rfc1036** [comment]
You need to run autoreconf --install: the source dumps created automatically by github based on git tags cannot contain generated files like configure.

**Comment by sharewax** [comment]
I suppose, that ./scripts/_init.sh should be changed for using git :)

**Comment by rfc1036** [comment]
If sten believes this to be an issue then he could add a file like http://git.kernel.org/cgit/utils/kernel/kmod/kmod.git/tree/bootstrap which runs autoreconf.

**Comment by sharewax** [comment]
Changed: commented hg:
```
# prepare
#hg pull -u
#hg log --style=changelog > ${BASE}/doc/ChangeLog

git pull -u
git log --date=short --pretty=format:'%ad [%h] [%an]: %s' > ${BASE}/doc/ChangeLog
```

**Comment by sharewax** [comment]
So I've created release tarball and all is ok. But, I suppose, some scripts/ should be updated ;)
