### ISSUE TITLE
active/backup teaming is not handled correctly

### ISSUE THREAD

**Issue by sharewax** [sspans/ladvd#21]
We are have issues (again) :)
Situation is the next. on Centos 7 from inactive link CDP packets are going with SRC MAC of teaming instead '00:00:00:00:00:00' how it was at Centos 5. It cause that Cisco learns MAC address on inactive interface and networking became unstable.
We have pcaps, if you need it.

**Comment by sspans** [comment]
Mmmm, that is indeed a bug. I'll try to get you a patch asap.

**Comment by sspans** [comment]
This will only happen if you don't have libteam-devel installed.
Please make sure you're building ladvd with this dependency installed.

```
sten@zem:~/git/ladvd$ sudo ./src/ladvd -foCd team0 | tcpdump -r- -e
reading from file -, link-type EN10MB (Ethernet)
ladvd 1.1.0 running
12:20:07.467094 00:00:00:00:00:00 (oui Ethernet) > 01:00:0c:cc:cc:cc (oui Unknown), 802.3, length 245: LLC, dsap SNAP (0xaa) Individual, ssap SNAP (0xaa) Command, ctrl 0x03: oui Cisco (0x00000c), pid CDP (0x2000): CDPv2, ttl: 180s, Device-ID 'zem.blinkenlights.nl', length 223
12:20:07.467413 00:00:00:00:00:00 (oui Ethernet) > 01:00:0c:cc:cc:cc (oui Unknown), 802.3, length 246: LLC, dsap SNAP (0xaa) Individual, ssap SNAP (0xaa) Command, ctrl 0x03: oui Cisco (0x00000c), pid CDP (0x2000): CDPv2, ttl: 180s, Device-ID 'zem.blinkenlights.nl', length 224
child exited with return code 0
quitting
```

**Comment by sharewax** [comment]
Oh yes, I didn't comment it. I'll rebuild packages.

**Comment by sharewax** [comment]
Yes, it works.
Also this is a bug at Cisco software (3750) because it shouldn't learn MAC from CDP package (but it do...)
In case of new Cisco devices (Nexus 5548) all works correctly.

**Comment by sharewax** [comment]
CDP doesnt update MAC address table and it is a layer 2 protocol that is used for discovering information about neighboring network devices. Because CDP operates at the Data Link layer, it does not need a network layer protocol, such as IP or IPX, to transfer information. CDP devices send out periodic advertisements to the MAC multicast address 0100.0ccc.cccc, every 60 seconds by default

CDP runs on all Cisco equipment such as routers, switches, bridges and access servers. It discovers information about neighboring devices such as the type of device and its capabilities, software version, the local and remote interface, and even configured network layer addresses

**Comment by sspans** [comment]
That indeed would seem to be a cisco bug. Closing this now.
