### ISSUE TITLE
ladvdc doesnt return all/any information most of the time

### ISSUE THREAD

**Issue by sandrotosi** [sspans/ladvd#23]
Hello,
we have tried ladvd 1.1.0 on our systems (no link aggregation, active/standby ports or whatever) but most of the times ladvdc doesnt return any information on any of the interfaces on the systems, sometimes it just returns info for eth0, and in very rare occasions it returns information on all the NICs.

**Comment by sspans** [comment]
That's unfortunate! 
Can you provide a bit more information to help figure out what exactly is going wrong?

- what os type/version are you running? (aka uname -a)
- can you run a tcpdump to show what kind of advertisements should be received?
- would it be possible to run ladvd in debug mode to show what's going on?

**Comment by sandrotosi** [comment]
thanks @sspans to follow this up, but unfortunately I'm afraid I dont have all the info you asked and we already moved away from ladvd. What I can tell you is taht we where using a 3.14.x kernel internally built.

**Comment by sspans** [comment]
Too bad, I guess this can be closed in that case.
