### ISSUE TITLE
Please generate a new official release

### ISSUE THREAD

**Issue by robbat2** [sspans/ladvd#27]
Several distributions seem to be shipping snapshots of Git or last release + patches.

Please generate a new official release to standardize what distributions have.

**Comment by sspans** [comment]
I'll be happy to generate a new release, do you have pointers to outstanding patches?

**Comment by robbat2** [comment]
No many outstanding patches, just minor and divergence since distros are using snapshots.

Debian:
https://anonscm.debian.org/cgit/users/md/ladvd.git/tree/debian/patches/no_werror
Fedora:
http://pkgs.fedoraproject.org/cgit/rpms/ladvd.git/tree/0001-fix-_BSD_SOURCE-and-_SVID_SOURCE-are-deprecated-use-.patch

Fedora also has backports of 6762be00532c90f5941e8d956706ba9fbcab0840 on their build, and some of the RPi builds are carrying the fix for #24 themselves.

**Comment by sharewax** [comment]
as for me, I've also suggested to bump the version. On the clear 1.1.0 we have issues with eating memory and not shown info, a few weeks ago I've rebuilt from the master and issues are gone.

**Comment by sspans** [comment]
I've released 1.1.1.
