### ISSUE TITLE
Packets with FCS not handled (CDP only tested)

### ISSUE THREAD

**Issue by jamesgohl** [sspans/ladvd#31]
I added another ethernet interface to my machine and I couldn't for the life me work out why ladvd wasn't handling CDP packets until I ran wireshark.  I discovered the new interface had FCS enabled, encapsulating an additional 4 bytes at the end of the frame.

I have located in your code where the packet gets rejected.  Function: `cdp_decode` in cdp.c
Line 384: the `my_log` call will output "Corrupt CDP packet: invalid TLV length".

I tested this by manually increasing the overall packet length by 4 bytes (where then subtracted from "length") on line 376.  It's as if it knows the packet length but trims off the FCS when parsing it.

Would you be able to fix or point me in the right direction?

I'm going to spend some time on it, I'll keep you posted but looking at your CV your have a ton of experience on network coding.

![2017-09-24-213152_1824x984_scrot](https://user-images.githubusercontent.com/1788271/30803549-84a579ca-a1d9-11e7-9748-42f2648c0607.png)

**Comment by sspans** [comment]
This should be simple to fix, can you share a tcpdump capture of the offending packet?
I would love to have this in the test-suite.
