### ISSUE TITLE
System serial number not correctly truncated under FreeBSD

### ISSUE THREAD

**Issue by courtland** [sspans/ladvd#37]
Under FreeBSD, the following line in src/sysinfo.c does not correctly truncate the SMBIOS system serial number to LLDP_INVENTORY_SIZE.

```kenv(KENV_GET, "smbios.system.serial", hinv->serial_number, len)```

The serial number from kenv can be longer than LLDP_INVENTORY_SIZE, which
means the above approach to truncating it loses the null terminator. This
causes the serial number and manufacturer to be concatenated together in
the resulting TLV in the packet. Certain LLDP agents will panic when receiving a packet where the inventory size is exceeded.

The following patch addressed my immediate problem, but obviously the same issue exists with similar uses of `kenv` (e.g. smbios.bios.version), so I have included it below instead of submitting a pull request. There is probably a better way to correctly truncate the string for all cases.

```
--- src/sysinfo.c.orig  2019-06-05 15:29:53 UTC
+++ src/sysinfo.c
@@ -218,6 +218,11 @@ void sysinfo_fetch(struct my_sysinfo *sysinfo) {
     kenv(KENV_GET, "smbios.system.version", hinv->hw_revision, len);
     kenv(KENV_GET, "smbios.bios.version", hinv->fw_revision, len);
     kenv(KENV_GET, "smbios.system.serial", hinv->serial_number, len);
+    // The serial number from kenv can be longer than LLDP_INVENTORY_SIZE, which
+    // means the above approach to truncating it loses the null terminator. This
+    // causes the serial number and manufacturer to be concatenated together in
+    // the resulting TLV in the packet.
+    hinv->serial_number[LLDP_INVENTORY_SIZE] = '\0';
     kenv(KENV_GET, "smbios.system.maker", hinv->manufacturer, len);
     kenv(KENV_GET, "smbios.system.product", hinv->model_name, len);
 #endif /* HAVE_KENV_H */
@@ -304,4 +309,5 @@ void sysinfo_forwarding(struct my_sysinfo *sysinfo) {
     }
 #endif
 }
+
```

**Comment by sspans** [comment]
solved by 10897ce
