### ISSUE TITLE
ladvd output is truncated if called via ssh/pssh/ansible

### ISSUE THREAD

**Issue by sharewax** [sspans/ladvd#39]
Hello.
If you have some network devices, like Cisco Nexus and ports are connected into FEXes, you have incorrect output from ladvd, if it calls via pssh/ssh/ansible command and can lead to incorrect port shutdown/up.

Examples: http://www.panooo.com/DevOps_memo1 (can be translated via google translate).
And our issue:

```
 >ssh ed-mgmt-1 'ladvdc -L'
Capability Codes:
	r - Repeater, B - Bridge, H - Host, R - Router, S - Switch,
	W - WLAN Access Point, C - DOCSIS Device, T - Telephone, O - Other

Device ID            Local Intf    Proto   Hold-time    Capability    Port ID
ed-n5596-fe-2        eno4          LLDP    100          B             Eth110/1/3
ed-n5596-fe-1        eno2          LLDP    115          B             Eth110/1/3
ed-n5596-be-1        eno1          LLDP    107          B             Eth110/1/3
ed-n5596-be-2        eno3          LLDP    106          B             Eth110/1/3
> ssh ed-mgmt-1
[root@ed-mgmt-1 ~]# ladvdc -L
Capability Codes:
	r - Repeater, B - Bridge, H - Host, R - Router, S - Switch,
	W - WLAN Access Point, C - DOCSIS Device, T - Telephone, O - Other

Device ID                      Local Intf    Proto   Hold-time    Capability    Port ID
ed-n5596-fe-2                  eno4          LLDP    117          B             Eth110/1/31
ed-n5596-fe-1                  eno2          LLDP    102          B             Eth110/1/31
ed-n5596-be-1                  eno1          LLDP    94           B             Eth110/1/31
ed-n5596-be-2                  eno3          LLDP    93           B             Eth110/1/31
```

it caused that default width is 80 symbols (src/cli.c, #define TERM_DEFAULT 80), but it doesn't fit if Cisco Nexus is used.

How can you suggest to avoid this behaviour ?

**Comment by sspans** [comment]
Well the easiest way would be to select a different output format.
Not sure if it's worth it to add a flag for this one.

**Comment by sharewax** [comment]
Yes, ssh -t helps somehow, but I think it's not correct to show not full info...
It should be aligned from right side, not left. Is it possible? As I see, only 1 symbol has been left. Can it be as in #37 bug?

**Comment by sspans** [comment]
This works as designed. With the default terminal width (80) hostnames get 20 and ports get 10.
Your port id's are 11 characters. The only way to resolve this is by making the whole thing dynamic based on the detected length of the hostnames  and port id's.

However life's gonna suck either way with only 80 chars available. Perhaps it's easier to just print out everything when terminal width cannot be detected.

**Comment by sharewax** [comment]
>  Perhaps it's easier to just print out everything when terminal width cannot be detected.


So? What we will do?

**Comment by sharewax** [comment]
I suppose that after that fix we should release new version :D

**Comment by sspans** [comment]
Can you confirm the merged code works for you?

**Comment by sharewax** [comment]
Yes, checked and it's worked!

**Comment by sharewax** [comment]
I've checked #40 (works!). If changes in #41 is only cosmetic, so I suppose it will work.

**Comment by sharewax** [comment]
Checked, let's close it, thank you very much! Let's think about version up :)
