### ISSUE TITLE
build failed on oracle linux 9

### ISSUE THREAD

**Issue by sharewax** [sspans/ladvd#44]
Hello. I just wanted to build ladvd for Oracle Linux 9 (I suppose the issue will be present for any RHEL based 9 version).
The same issue as in debian based https://www.mail-archive.com/debian-bugs-rc@lists.debian.org/msg598937.html

Log is here: https://gist.github.com/sharewax/568a34cbf9b6f79aa34d2b0cb68e6fef

All is building ok with Centos7 (gcc 4.5).

GCC on OL9 is 11

**Comment by sharewax** [comment]
It can be fixed by
```make CFLAGS+=-DMAXPATHLEN=PATH_MAX %{?_smp_mflags}```
but it seems quite strange and should be fixed in spec file or on detection of fresh gcc.

**Comment by sspans** [comment]
Solved by #45
